[project]
dependencies = ["mcp[cli]>=1.6.0", "pyvista[all]>=0.44.2"]
description = "Add your description here"
name = "pyvista-mcp-server"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
